# Generated by Django 4.2.7 on 2024-01-27 10:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CrushResponse",
            new_name="Proposal",
        ),
    ]
