# Generated by Django 4.2.7 on 2024-01-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alter_proposal_response"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposal",
            name="response",
            field=models.CharField(max_length=3),
        ),
    ]
