# Generated by Django 4.2.7 on 2024-01-29 12:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_alter_proposal_response"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
