# Generated by Django 4.2.7 on 2024-01-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_proposal_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
